apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app
  namespace: hospital
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: nginx:latest
          ports:
            - containerPort: 80
